In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from ast import literal_eval
import geopandas as gpd

C:\Users\abreunig\AppData\Local\Temp\2\ipykernel_12904\305143733.py:5: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd

In [2]:
CO_URL = 'https://www.mountainproject.com/area/105708956/colorado'

In [3]:
html_str = requests.get(CO_URL).content
soup = BeautifulSoup(html_str, 'html.parser')

In [4]:
co_areas = {}
for link in soup.find_all('div', {'class': 'lef-nav-row'}):
    for url in link.find_all('a', href=True):
        print(url.contents)
        print(url['href'])
        co_areas[url.contents[0]] = url['href']

['10 Mile Canyon']
https://www.mountainproject.com/area/106817352/10-mile-canyon
['Alpine Rock']
https://www.mountainproject.com/area/105744466/alpine-rock
['Aspen Glen Campground Bouldering']
https://www.mountainproject.com/area/122921638/aspen-glen-campground-bouldering
['Black Hawk']
https://www.mountainproject.com/area/121624024/black-hawk
['Boulder']
https://www.mountainproject.com/area/105801420/boulder
['Breckenridge']
https://www.mountainproject.com/area/108289116/breckenridge
['Bridge']
https://www.mountainproject.com/area/124014835/bridge
['Broomfield']
https://www.mountainproject.com/area/122059772/broomfield
['Broomfield Boulders']
https://www.mountainproject.com/area/123696872/broomfield-boulders
['Buena Vista']
https://www.mountainproject.com/area/105744391/buena-vista
['Canon City']
https://www.mountainproject.com/area/105800427/canon-city
['Carbondale Area']
https://www.mountainproject.com/area/105802064/carbondale-area
['Cataract Lake (Heeney, Colorado)']
https://www.mountainproject.com/area/106562735/cataract-lake-heeney-colorado
['CO Ice & Mixed']
https://www.mountainproject.com/area/105807296/co-ice-mixed
['Coal Creek Canyon']
https://www.mountainproject.com/area/108580517/coal-creek-canyon
['Colorado Springs']
https://www.mountainproject.com/area/105800307/colorado-springs
['Craig/Hamilton Area']
https://www.mountainproject.com/area/123438738/craighamilton-area
['Crested Butte']
https://www.mountainproject.com/area/107163609/crested-butte
['Crestone']
https://www.mountainproject.com/area/118890747/crestone
['Cross Mountain Boulders']
https://www.mountainproject.com/area/113745735/cross-mountain-boulders
['Denver Metropolitan Area Bouldering and Buildering']
https://www.mountainproject.com/area/121107762/denver-metropolitan-area-bouldering-and-buildering
['Denver South']
https://www.mountainproject.com/area/105802558/denver-south
['Dumont vicinity']
https://www.mountainproject.com/area/107316644/dumont-vicinity
['Durango']
https://www.mountainproject.com/area/105819665/durango
['Eagle/Vail/Minturn/Red Cliff']
https://www.mountainproject.com/area/105802428/eaglevailminturnred-cliff
['Eldora']
https://www.mountainproject.com/area/105993461/eldora
['Elkhead Mountains']
https://www.mountainproject.com/area/108199808/elkhead-mountains
['Empire']
https://www.mountainproject.com/area/105744285/empire
['Equinox Gardens']
https://www.mountainproject.com/area/109569174/equinox-gardens
['Estes Park Valley']
https://www.mountainproject.com/area/105801865/estes-park-valley
['Fairplay']
https://www.mountainproject.com/area/106247375/fairplay
['Flat Tops']
https://www.mountainproject.com/area/122585207/flat-tops
['Fort Collins']
https://www.mountainproject.com/area/105800315/fort-collins
['Four Corners Area']
https://www.mountainproject.com/area/121759253/four-corners-area
['Fremont Pass']
https://www.mountainproject.com/area/105849739/fremont-pass
['Frisco Boulders']
https://www.mountainproject.com/area/106828013/frisco-boulders
['Georgetown']
https://www.mountainproject.com/area/105744355/georgetown
['Glenwood Springs']
https://www.mountainproject.com/area/105802032/glenwood-springs
['Gold Butte']
https://www.mountainproject.com/area/113453081/gold-butte
['Golden']
https://www.mountainproject.com/area/105800295/golden
['Gore Canyon']
https://www.mountainproject.com/area/112120092/gore-canyon
['Grand County / Fraser Valley']
https://www.mountainproject.com/area/107225279/grand-county-fraser-valley
['Grand Junction Area']
https://www.mountainproject.com/area/105802036/grand-junction-area
['Green Mountain Reservoir']
https://www.mountainproject.com/area/112107131/green-mountain-reservoir
['Gross Reservoir']
https://www.mountainproject.com/area/107730328/gross-reservoir
['Gunnison']
https://www.mountainproject.com/area/105802040/gunnison
['Handies Peak']
https://www.mountainproject.com/area/119123794/handies-peak
['Idaho Springs']
https://www.mountainproject.com/area/105744276/idaho-springs
['Independence Pass']
https://www.mountainproject.com/area/105744331/independence-pass
['Irish Canyon']
https://www.mountainproject.com/area/107483925/irish-canyon
['Keystone a.k.a. Montezuma']
https://www.mountainproject.com/area/105744388/keystone-aka-montezuma
['Leadville']
https://www.mountainproject.com/area/108775092/leadville
['Lyons']
https://www.mountainproject.com/area/105802046/lyons
['Montrose']
https://www.mountainproject.com/area/106454069/montrose
['Morrison/Evergreen/Littleton']
https://www.mountainproject.com/area/105802697/morrisonevergreenlittleton
['Naturita and Paradox Valley']
https://www.mountainproject.com/area/105925205/naturita-and-paradox-valley
['Ouray vicinity (rock)']
https://www.mountainproject.com/area/105846105/ouray-vicinity-rock
['Pagosa Springs']
https://www.mountainproject.com/area/106221644/pagosa-springs
['Parachute/ Battlement Mesa']
https://www.mountainproject.com/area/118952860/parachute-battlement-mesa
['Pawnee Grasslands']
https://www.mountainproject.com/area/107358695/pawnee-grasslands
['Peak to Peak Highway']
https://www.mountainproject.com/area/123790753/peak-to-peak-highway
['Rifle']
https://www.mountainproject.com/area/105802424/rifle
['Rollins Pass']
https://www.mountainproject.com/area/119388109/rollins-pass
['San Luis Valley']
https://www.mountainproject.com/area/105800418/san-luis-valley
['Silver Basin']
https://www.mountainproject.com/area/112130105/silver-basin
['Silver Plume']
https://www.mountainproject.com/area/105744273/silver-plume
['Silverton area']
https://www.mountainproject.com/area/106444659/silverton-area
['South Platte']
https://www.mountainproject.com/area/105797719/south-platte
['Spanish Peaks']
https://www.mountainproject.com/area/105801651/spanish-peaks
['Steamboat Springs']
https://www.mountainproject.com/area/105882626/steamboat-springs
['Telluride/Norwood area']
https://www.mountainproject.com/area/105969849/telluridenorwood-area
['Vogel Canyon']
https://www.mountainproject.com/area/107841192/vogel-canyon
['Weston Pass-(Weston Wall)']
https://www.mountainproject.com/area/106689909/weston-pass-weston-wall
['Wet Mountains, The']
https://www.mountainproject.com/area/105801976/the-wet-mountains
['Wild Mountain']
https://www.mountainproject.com/area/119270576/wild-mountain

In [5]:
co_areas

{'10 Mile Canyon': 'https://www.mountainproject.com/area/106817352/10-mile-canyon',
 'Alpine Rock': 'https://www.mountainproject.com/area/105744466/alpine-rock',
 'Aspen Glen Campground Bouldering': 'https://www.mountainproject.com/area/122921638/aspen-glen-campground-bouldering',
 'Black Hawk': 'https://www.mountainproject.com/area/121624024/black-hawk',
 'Boulder': 'https://www.mountainproject.com/area/105801420/boulder',
 'Breckenridge': 'https://www.mountainproject.com/area/108289116/breckenridge',
 'Bridge': 'https://www.mountainproject.com/area/124014835/bridge',
 'Broomfield': 'https://www.mountainproject.com/area/122059772/broomfield',
 'Broomfield Boulders': 'https://www.mountainproject.com/area/123696872/broomfield-boulders',
 'Buena Vista': 'https://www.mountainproject.com/area/105744391/buena-vista',
 'Canon City': 'https://www.mountainproject.com/area/105800427/canon-city',
 'Carbondale Area': 'https://www.mountainproject.com/area/105802064/carbondale-area',
 'Cataract Lake (Heeney, Colorado)': 'https://www.mountainproject.com/area/106562735/cataract-lake-heeney-colorado',
 'CO Ice & Mixed': 'https://www.mountainproject.com/area/105807296/co-ice-mixed',
 'Coal Creek Canyon': 'https://www.mountainproject.com/area/108580517/coal-creek-canyon',
 'Colorado Springs': 'https://www.mountainproject.com/area/105800307/colorado-springs',
 'Craig/Hamilton Area': 'https://www.mountainproject.com/area/123438738/craighamilton-area',
 'Crested Butte': 'https://www.mountainproject.com/area/107163609/crested-butte',
 'Crestone': 'https://www.mountainproject.com/area/118890747/crestone',
 'Cross Mountain Boulders': 'https://www.mountainproject.com/area/113745735/cross-mountain-boulders',
 'Denver Metropolitan Area Bouldering and Buildering': 'https://www.mountainproject.com/area/121107762/denver-metropolitan-area-bouldering-and-buildering',
 'Denver South': 'https://www.mountainproject.com/area/105802558/denver-south',
 'Dumont vicinity': 'https://www.mountainproject.com/area/107316644/dumont-vicinity',
 'Durango': 'https://www.mountainproject.com/area/105819665/durango',
 'Eagle/Vail/Minturn/Red Cliff': 'https://www.mountainproject.com/area/105802428/eaglevailminturnred-cliff',
 'Eldora': 'https://www.mountainproject.com/area/105993461/eldora',
 'Elkhead Mountains': 'https://www.mountainproject.com/area/108199808/elkhead-mountains',
 'Empire': 'https://www.mountainproject.com/area/105744285/empire',
 'Equinox Gardens': 'https://www.mountainproject.com/area/109569174/equinox-gardens',
 'Estes Park Valley': 'https://www.mountainproject.com/area/105801865/estes-park-valley',
 'Fairplay': 'https://www.mountainproject.com/area/106247375/fairplay',
 'Flat Tops': 'https://www.mountainproject.com/area/122585207/flat-tops',
 'Fort Collins': 'https://www.mountainproject.com/area/105800315/fort-collins',
 'Four Corners Area': 'https://www.mountainproject.com/area/121759253/four-corners-area',
 'Fremont Pass': 'https://www.mountainproject.com/area/105849739/fremont-pass',
 'Frisco Boulders': 'https://www.mountainproject.com/area/106828013/frisco-boulders',
 'Georgetown': 'https://www.mountainproject.com/area/105744355/georgetown',
 'Glenwood Springs': 'https://www.mountainproject.com/area/105802032/glenwood-springs',
 'Gold Butte': 'https://www.mountainproject.com/area/113453081/gold-butte',
 'Golden': 'https://www.mountainproject.com/area/105800295/golden',
 'Gore Canyon': 'https://www.mountainproject.com/area/112120092/gore-canyon',
 'Grand County / Fraser Valley': 'https://www.mountainproject.com/area/107225279/grand-county-fraser-valley',
 'Grand Junction Area': 'https://www.mountainproject.com/area/105802036/grand-junction-area',
 'Green Mountain Reservoir': 'https://www.mountainproject.com/area/112107131/green-mountain-reservoir',
 'Gross Reservoir': 'https://www.mountainproject.com/area/107730328/gross-reservoir',
 'Gunnison': 'https://www.mountainproject.com/area/105802040/gunnison',
 'Handies Peak': 'https://www.mountainproject.com/area/119123794/handies-peak',
 'Idaho Springs': 'https://www.mountainproject.com/area/105744276/idaho-springs',
 'Independence Pass': 'https://www.mountainproject.com/area/105744331/independence-pass',
 'Irish Canyon': 'https://www.mountainproject.com/area/107483925/irish-canyon',
 'Keystone a.k.a. Montezuma': 'https://www.mountainproject.com/area/105744388/keystone-aka-montezuma',
 'Leadville': 'https://www.mountainproject.com/area/108775092/leadville',
 'Lyons': 'https://www.mountainproject.com/area/105802046/lyons',
 'Montrose': 'https://www.mountainproject.com/area/106454069/montrose',
 'Morrison/Evergreen/Littleton': 'https://www.mountainproject.com/area/105802697/morrisonevergreenlittleton',
 'Naturita and Paradox Valley': 'https://www.mountainproject.com/area/105925205/naturita-and-paradox-valley',
 'Ouray vicinity (rock)': 'https://www.mountainproject.com/area/105846105/ouray-vicinity-rock',
 'Pagosa Springs': 'https://www.mountainproject.com/area/106221644/pagosa-springs',
 'Parachute/ Battlement Mesa': 'https://www.mountainproject.com/area/118952860/parachute-battlement-mesa',
 'Pawnee Grasslands': 'https://www.mountainproject.com/area/107358695/pawnee-grasslands',
 'Peak to Peak Highway': 'https://www.mountainproject.com/area/123790753/peak-to-peak-highway',
 'Rifle': 'https://www.mountainproject.com/area/105802424/rifle',
 'Rollins Pass': 'https://www.mountainproject.com/area/119388109/rollins-pass',
 'San Luis Valley': 'https://www.mountainproject.com/area/105800418/san-luis-valley',
 'Silver Basin': 'https://www.mountainproject.com/area/112130105/silver-basin',
 'Silver Plume': 'https://www.mountainproject.com/area/105744273/silver-plume',
 'Silverton area': 'https://www.mountainproject.com/area/106444659/silverton-area',
 'South Platte': 'https://www.mountainproject.com/area/105797719/south-platte',
 'Spanish Peaks': 'https://www.mountainproject.com/area/105801651/spanish-peaks',
 'Steamboat Springs': 'https://www.mountainproject.com/area/105882626/steamboat-springs',
 'Telluride/Norwood area': 'https://www.mountainproject.com/area/105969849/telluridenorwood-area',
 'Vogel Canyon': 'https://www.mountainproject.com/area/107841192/vogel-canyon',
 'Weston Pass-(Weston Wall)': 'https://www.mountainproject.com/area/106689909/weston-pass-weston-wall',
 'Wet Mountains, The': 'https://www.mountainproject.com/area/105801976/the-wet-mountains',
 'Wild Mountain': 'https://www.mountainproject.com/area/119270576/wild-mountain'}

In [6]:
colorado_areas = pd.DataFrame.from_dict(co_areas, orient='index')
colorado_areas

                                                                                  0
10 Mile Canyon                    https://www.mountainproject.com/area/106817352...
Alpine Rock                       https://www.mountainproject.com/area/105744466...
Aspen Glen Campground Bouldering  https://www.mountainproject.com/area/122921638...
Black Hawk                        https://www.mountainproject.com/area/121624024...
Boulder                           https://www.mountainproject.com/area/105801420...
...                                                                             ...
Telluride/Norwood area            https://www.mountainproject.com/area/105969849...
Vogel Canyon                      https://www.mountainproject.com/area/107841192...
Weston Pass-(Weston Wall)         https://www.mountainproject.com/area/106689909...
Wet Mountains, The                https://www.mountainproject.com/area/105801976...
Wild Mountain                     https://www.mountainproject.com/area/119270576...

[75 rows x 1 columns]

In [7]:
def get_coords(contents_list):
    coord_str = contents_list[0].strip() # remove linebreak/whitespace
    coord_list = coord_str.split(',')
    lat = float(coord_list[0])
    lng = float(coord_list[1])

    return lat, lng

In [8]:
all_crags = pd.DataFrame()
for area, url in colorado_areas.iterrows():
    print(area)
    crag_coords = {}
    html_str = requests.get(url[0]).content
    area_soup = BeautifulSoup(html_str, 'html.parser')
    
    for link in area_soup.find_all('div', {'class': 'lef-nav-row'}):
        for url in link.find_all('a', href=True):
            crag_name = url.contents[0]

            html_str = requests.get(url['href']).content
            crag = BeautifulSoup(html_str, 'html.parser')
            
            for c in crag.find_all('div', {'class': 'col-md-3 left-nav float-md-left mb-2'}):
                for header in c.find_all('h3'):
                    if 'Areas in' in header.text:
                        print(f'Has subareas: {header.text}')

                        # get subarea names
                        for link in crag.find_all('div', {'class': 'lef-nav-row'}):
                            for url in link.find_all('a', href=True):
                                sub_crag = url.contents[0]
                                print(crag_name)
                                html_str = requests.get(url['href']).content
                                subarea_soup = BeautifulSoup(html_str, 'html.parser')

                                for c in subarea_soup.find_all('div', {'class': 'small'}):
                                    # Grabbing lat + long
                                    for text in c.find_all('td'):
                                        if '-1' in text.text:
                                            contents_list = text.contents
                                            lat, lng = get_coords(contents_list)
                                            #print(lat, lng)
                                            crag_coords = {'Lat': lat, 'Long': lng}
                                            #print(crag_coords)


                                # total climbs stats
                                for c in subarea_soup.find_all('div', {'class': 'col-lg-6 text-xs-center', 'id': 'route-count-container'}):
                                    script_tag = c.find_all('script')[1].string
                                    if script_tag:
                                        tag = script_tag.split(';')[0].replace(' ', '').replace('\n', '')
                                        data = tag.split('google.visualization.arrayToDataTable(')[1].rstrip(')')
                                        data = literal_eval(data)[1:]
                                        climb_dict = {k[0]: k[1] for k in data}
                                        crag_dict = climb_dict | crag_coords
                                        crag_id = pd.MultiIndex.from_tuples([(crag_name, sub_crag)], name=['Area', 'Crag'])
                                        crag_df = pd.DataFrame(crag_dict, index=crag_id)
                                        all_crags = pd.concat([all_crags, crag_df])


                    else:
                        print(f'No subareas: {header.text}')
                        
                        for c in crag.find_all('div', {'class': 'small'}):
                            # Grabbing lat + long
                            for text in c.find_all('td'):
                                if '-1' in text.text:
                                    contents_list = text.contents
                                    lat, lng = get_coords(contents_list)
                                    #print(lat, lng)
                                    crag_coords = {'Lat': lat, 'Long': lng}
                                    #print(crag_coords)


                        # total climbs stats
                        for c in crag.find_all('div', {'class': 'col-lg-6 text-xs-center', 'id': 'route-count-container'}):
                            script_tag = c.find_all('script')[1].string
                            if script_tag:
                                tag = script_tag.split(';')[0].replace(' ', '').replace('\n', '')
                                data = tag.split('google.visualization.arrayToDataTable(')[1].rstrip(')')
                                data = literal_eval(data)[1:]
                                climb_dict = {k[0]: k[1] for k in data}
                                crag_dict = climb_dict | crag_coords
                                crag_id = pd.MultiIndex.from_tuples([(area, crag_name)], name=['Area', 'Crag'])
                                crag_df = pd.DataFrame(crag_dict, index=crag_id)
                                all_crags = pd.concat([all_crags, crag_df])
                                
                                #all_crag_ids.append(crag_tuple)

10 Mile Canyon
No subareas: Routes in 10 Mile Tower
Has subareas: Areas in Brick Wall/Alcoves
Brick Wall/Alcoves
Brick Wall/Alcoves
No subareas: Routes in The Cache Wall
No subareas: Routes in Desperation Wall
Has subareas: Areas in The Diamond /Officer's Wall Massif
Diamond /Officer's Wall Massif, The
Diamond /Officer's Wall Massif, The
No subareas: Routes in The Dome
No subareas: Routes in Halfway Rock
No subareas: Routes in Mount Royal (near Frisco)
No subareas: Routes in Officer's Gulch West
No subareas: Routes in The Shire
Has subareas: Areas in Smile Wall
Smile Wall
Smile Wall
No subareas: Routes in Spider Boulder
No subareas: Routes in Sunshine Buttress (aka Wichita Wall)
Has subareas: Areas in Sunshine, Ding Dong Dome Bouldering
Sunshine, Ding Dong Dome Bouldering
No subareas: Routes in Teeter Top
No subareas: Routes in Wheeler Lakes
No subareas: Routes in White Cliff
Alpine Rock
No subareas: Routes in Capitol Peak
No subareas: Routes in Chimneys of Treasure
No subareas: Routes in The Citadel
No subareas: Routes in Frasco's Toe
Has subareas: Areas in Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
Gore Mountain Range
No subareas: Routes in Grizzly Peak
Has subareas: Areas in Holy Cross Wilderness
Holy Cross Wilderness
Holy Cross Wilderness
Holy Cross Wilderness
No subareas: Routes in Ice Mountain
Has subareas: Areas in Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
Indian Peaks
No subareas: Routes in La Plata
No subareas: Routes in Long / Multi-area Traverses
No subareas: Routes in Maroon Bells
No subareas: Routes in Mount of the Holy Cross
Has subareas: Areas in Mt. Bierstadt
Mt. Bierstadt
Mt. Bierstadt
Mt. Bierstadt
Mt. Bierstadt
Has subareas: Areas in Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Mt. Evans
Has subareas: Areas in Northstar Mountain
Northstar Mountain
Northstar Mountain
No subareas: Routes in Pettingell Peak
No subareas: Routes in Pyramid Peak
No subareas: Routes in Quandary Peak
Has subareas: Areas in RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
RMNP - Rock
Has subareas: Areas in San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
San Juans
Has subareas: Areas in Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
Sangre de Cristo Range
No subareas: Routes in Sawtooth Ridge, Mt. Bierstadt/Evans combo
Has subareas: Areas in Tenmile Range
Tenmile Range
Tenmile Range
Tenmile Range
Tenmile Range
No subareas: Routes in Torrey's Peak
Aspen Glen Campground Bouldering
Black Hawk
No subareas: Routes in The Ameristar
Boulder
No subareas: Routes in Badbridges
No subareas: Routes in Bear creek elementary
Has subareas: Areas in Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Boulder Canyon
Has subareas: Areas in City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
City of Boulder
Has subareas: Areas in Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Eldorado Canyon State Park
Has subareas: Areas in Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Eldorado Mountain
Has subareas: Areas in Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Flagstaff
Has subareas: Areas in Flatirons
Flatirons
Flatirons
Flatirons
Flatirons
Has subareas: Areas in Lefthand Canyon
Lefthand Canyon
Lefthand Canyon
Lefthand Canyon
Lefthand Canyon
Has subareas: Areas in Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
Mount Sanitas
No subareas: Routes in The Spotlight
Has subareas: Areas in Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Upper Dream Canyon
Breckenridge
No subareas: Routes in -
No subareas: Routes in The Peak 9 Boulder
No subareas: Routes in Raspberry Boulders
Bridge
Broomfield
Broomfield Boulders
Buena Vista
Has subareas: Areas in Arkansas Valley Bouldering
*Arkansas Valley Bouldering
*Arkansas Valley Bouldering
*Arkansas Valley Bouldering
*Arkansas Valley Bouldering
No subareas: Routes in Almost A Tunnel
No subareas: Routes in Americus Wall
No subareas: Routes in Below The Arch Crag
No subareas: Routes in Billy's Buttress
No subareas: Routes in Bob's Rock
No subareas: Routes in Bottom of the Staircase
No subareas: Routes in Briar Patch
Has subareas: Areas in Brown's Canyon National Monument
Brown's Canyon National Monument
Brown's Canyon National Monument
No subareas: Routes in Bullet Review Rock
No subareas: Routes in Buzzsaw Dome
Has subareas: Areas in Castle Rock Gulch
Castle Rock Gulch
No subareas: Routes in Cat's Claw Crag (C3)
Has subareas: Areas in Chalk Creek Canyon
Chalk Creek Canyon
Chalk Creek Canyon
Chalk Creek Canyon
Chalk Creek Canyon
Chalk Creek Canyon
No subareas: Routes in Chief's Head
No subareas: Routes in Chocolate Tower
No subareas: Routes in Christmas Crag
Has subareas: Areas in Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
Climbing Areas 53-64
No subareas: Routes in Clohesy Lake
No subareas: Routes in Davis Face
No subareas: Routes in Day Dream Crag
No subareas: Routes in Duck Wall
No subareas: Routes in Elephant Rock
No subareas: Routes in The Granite Block
Has subareas: Areas in Granite Campground Area
Granite Campground Area
Granite Campground Area
Granite Campground Area
Granite Campground Area
Granite Campground Area
No subareas: Routes in Holy Water Wall
No subareas: Routes in The Leaning Wall
Has subareas: Areas in Lilliput
Lilliput
Lilliput
No subareas: Routes in Loaf of Bread & Bun (in the Land of Crank)
No subareas: Routes in Midline Slab
No subareas: Routes in The Milt Wall
No subareas: Routes in The Museum
No subareas: Routes in On The Hill
No subareas: Routes in Pleasure Dome
No subareas: Routes in Poncho's Vista
No subareas: Routes in Pump Station
No subareas: Routes in Rabbit Ridge
Has subareas: Areas in The Ridge
Ridge, The
Ridge, The
No subareas: Routes in The River Chamber
No subareas: Routes in The Rock Pile
No subareas: Routes in The Roost
No subareas: Routes in South Split Rock
No subareas: Routes in Split Rock
Has subareas: Areas in St. Elmo
St. Elmo
No subareas: Routes in There is Spice to Life Tower.
No subareas: Routes in The Three Amigos
No subareas: Routes in Tool Wall / Tool Tower
No subareas: Routes in Transmitter Tower
No subareas: Routes in Trout Climbing in America
No subareas: Routes in Turbo Big Tower
Has subareas: Areas in Turtle Rocks, Baby Turtle, and The Corridor
Turtle Rocks, Baby Turtle, and The Corridor
Turtle Rocks, Baby Turtle, and The Corridor
Turtle Rocks, Baby Turtle, and The Corridor
No subareas: Routes in Water Front
Has subareas: Areas in White Noise
White Noise
Canon City
Has subareas: Areas in 257
257
257
257
Has subareas: Areas in Buckskin Crags
Buckskin Crags
Buckskin Crags
Buckskin Crags
Buckskin Crags
Buckskin Crags
Buckskin Crags
No subareas: Routes in Coaldale
Has subareas: Areas in Four Mile Creek Bouldering
Four Mile Creek Bouldering
Four Mile Creek Bouldering
Four Mile Creek Bouldering
Four Mile Creek Bouldering
No subareas: Routes in Gothic Cathedral
Has subareas: Areas in Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Phantom Canyon
Has subareas: Areas in Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Shelf Road
Has subareas: Areas in Table Mountain South
Table Mountain South
Carbondale Area
Has subareas: Areas in Coal Creek Boulders
Coal Creek Boulders
Coal Creek Boulders
Coal Creek Boulders
Coal Creek Boulders
Coal Creek Boulders
No subareas: Routes in Downtown Carbondale
Has subareas: Areas in The Frying Pan
Frying Pan, The
Frying Pan, The
Frying Pan, The
Frying Pan, The
Frying Pan, The
Has subareas: Areas in Lizard Lake
Lizard Lake
No subareas: Routes in Low Hanging Fruit Wall
Has subareas: Areas in The Narrows
Narrows, The
Narrows, The
Narrows, The
Narrows, The
Narrows, The
Narrows, The
Narrows, The
Has subareas: Areas in Redstone Area
Redstone Area
Redstone Area
Redstone Area
Redstone Area
Redstone Area
Cataract Lake (Heeney, Colorado)
CO Ice & Mixed
No subareas: Routes in Arapahoe Basin Area
No subareas: Routes in Bierstadt Ice
No subareas: Routes in Big Thompson Canyon Ice
No subareas: Routes in Black Canyon National Park (Ice)
Has subareas: Areas in Blue Mesa (near Gunnison)
Blue Mesa (near Gunnison)
Blue Mesa (near Gunnison)
Has subareas: Areas in Boulder Canyon - Ice
Boulder Canyon - Ice
Boulder Canyon - Ice
Boulder Canyon - Ice
Boulder Canyon - Ice
Boulder Canyon - Ice
Boulder Canyon - Ice
No subareas: Routes in Buena Vista
Has subareas: Areas in Castlewood Canyon State Park - Ice
Castlewood Canyon State Park - Ice
Castlewood Canyon State Park - Ice
No subareas: Routes in Chama Basin
Has subareas: Areas in Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Cimarron Mountains
Has subareas: Areas in Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Clear Creek Canyon - Ice
Has subareas: Areas in Coal Creek Canyon
Coal Creek Canyon
No subareas: Routes in Colorado National Monument (Ice)
Has subareas: Areas in Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
Colorado Springs & vicinity
No subareas: Routes in Creede/Spring Creek Pass
No subareas: Routes in Crested Butte
Has subareas: Areas in Durango
Durango
Durango
Durango
Durango
Durango
Durango
Durango
Durango
Has subareas: Areas in Eldora
Eldora
No subareas: Routes in Evergreen - Bear Creek ice
No subareas: Routes in Flatirons
No subareas: Routes in Ft. Collins
No subareas: Routes in Gateway/Naturita
No subareas: Routes in Georgetown Ice
No subareas: Routes in Glenwood Canyon Ice
No subareas: Routes in Gore Range
No subareas: Routes in Grand Mesa
No subareas: Routes in Holy Cross/Notch Mountain
No subareas: Routes in Hoosier Pass/Lincoln Fall
No subareas: Routes in Idaho Springs Water Wheel
Has subareas: Areas in Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Indian Peaks & James Peak Wilderness Areas
Has subareas: Areas in Lake City
Lake City
Lake City
Lake City
Lake City
Lake City
Lake City
Lake City
Lake City
Lake City
Has subareas: Areas in Leadville Ice
Leadville Ice
Leadville Ice
No subareas: Routes in Lookout Mountain Dry Tooling Area
No subareas: Routes in Lover's Leap
No subareas: Routes in McClellan Mountain (Gray's & Torrey's area)
Has subareas: Areas in Moffatt Tunnel
Moffatt Tunnel
Moffatt Tunnel
No subareas: Routes in Mt. Evans - mixed, couloirs
No subareas: Routes in North Table Mountain
Has subareas: Areas in Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
Ouray (Ice/Mixed)
No subareas: Routes in Parachute
No subareas: Routes in Poudre Canyon
Has subareas: Areas in Quandary Peak/Blue Lakes
Quandary Peak/Blue Lakes
Quandary Peak/Blue Lakes
Quandary Peak/Blue Lakes
Quandary Peak/Blue Lakes
Quandary Peak/Blue Lakes
Has subareas: Areas in Redstone
Redstone
Redstone
Has subareas: Areas in Rifle Mountain Park
Rifle Mountain Park
Has subareas: Areas in RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
RMNP - Mixed/Ice
No subareas: Routes in Royal Gorge/Canon City
Has subareas: Areas in Sangre De Cristo Mountains Ice
Sangre De Cristo Mountains Ice
Sangre De Cristo Mountains Ice
Sangre De Cristo Mountains Ice
Sangre De Cristo Mountains Ice
Sangre De Cristo Mountains Ice
No subareas: Routes in Silverplume & vicinity
Has subareas: Areas in Silverton
Silverton
Silverton
Silverton
Silverton
Silverton
Silverton
Silverton
Silverton
Silverton
No subareas: Routes in Sneffels Range
Has subareas: Areas in St. Vrain ice
St. Vrain ice
St. Vrain ice
St. Vrain ice
St. Vrain ice
No subareas: Routes in Staunton State Park Ice
Has subareas: Areas in Steamboat Springs
Steamboat Springs
Has subareas: Areas in Telluride
Telluride
Telluride
Telluride
Telluride
Telluride
Telluride
Telluride
Telluride
No subareas: Routes in Tenmile Canyon aka Officer's Gulch
No subareas: Routes in Unaweep Canyon
Has subareas: Areas in Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
Vail Ice
No subareas: Routes in Westminster Ice Park
No subareas: Routes in Wheeler Mountain
Has subareas: Areas in Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Wolf Creek Pass/San Luis Valley Ice
Coal Creek Canyon
No subareas: Routes in 6th Flatiron (Blue Mountain Dr.)
No subareas: Routes in Echo Rock (AKA The Scoop)
Has subareas: Areas in Pinecliffe
Pinecliffe
Pinecliffe
Pinecliffe
No subareas: Routes in Sisters Rock
Colorado Springs
Has subareas: Areas in Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
Air Force Academy
No subareas: Routes in Blodgett Peak
No subareas: Routes in Colorado College
No subareas: Routes in Ed Rock
No subareas: Routes in Englemann Canyon (submitted as Ruxton Canyon, Manitou Springs)
No subareas: Routes in Functioning Artisanal Grotto
Has subareas: Areas in Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
Garden of the Gods
No subareas: Routes in Graffiti Falls
No subareas: Routes in Monument Rock
Has subareas: Areas in Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
Mount Herman
No subareas: Routes in Mt. Manitou
Has subareas: Areas in North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon
North Cheyenne Canyon

In [14]:
all_crags = all_crags.fillna(0)
all_crags.head()

                                     Sport       Lat       Long  Trad  \
Area               Crag
10 Mile Canyon     10 Mile Tower       1.0  39.57010 -106.11985   0.0
Brick Wall/Alcoves Alcoves, The        0.0  39.56660 -106.12615   0.0
                   Brick Wall          0.0  39.56637 -106.12630   1.0
10 Mile Canyon     Cache Wall, The     6.0  39.56147 -106.13202   1.0
                   Desperation Wall    4.0  39.51999 -106.14030   2.0

                                     Toprope  Boulder  Alpine  Aid  Ice  \
Area               Crag
10 Mile Canyon     10 Mile Tower         0.0      0.0     0.0  0.0  0.0
Brick Wall/Alcoves Alcoves, The          0.0      0.0     0.0  0.0  0.0
                   Brick Wall            1.0      0.0     0.0  0.0  0.0
10 Mile Canyon     Cache Wall, The       0.0      0.0     0.0  0.0  0.0
                   Desperation Wall      3.0      3.0     0.0  0.0  0.0

                                     Mixed  Total Climbs  \
Area               Crag
10 Mile Canyon     10 Mile Tower       0.0           1.0
Brick Wall/Alcoves Alcoves, The        0.0           0.0
                   Brick Wall          0.0           2.0
10 Mile Canyon     Cache Wall, The     0.0           7.0
                   Desperation Wall    0.0          12.0

                                                        geometry
Area               Crag
10 Mile Canyon     10 Mile Tower     POINT (-106.11985 39.57010)
Brick Wall/Alcoves Alcoves, The      POINT (-106.12615 39.56660)
                   Brick Wall        POINT (-106.12630 39.56637)
10 Mile Canyon     Cache Wall, The   POINT (-106.13202 39.56147)
                   Desperation Wall  POINT (-106.14030 39.51999)

In [15]:
all_crags['Total Climbs'] = all_crags.apply(lambda x: x['Sport'] + x['Trad'] + x['Toprope'] + x['Boulder'] + x['Alpine'] + x['Ice'] + x['Aid'] + x['Mixed'], axis=1)

In [16]:
all_crags.to_csv('all_crags_colorado_full.csv')

In [17]:
gdf = gpd.GeoDataFrame(all_crags, geometry=gpd.points_from_xy(all_crags['Long'], all_crags['Lat']), crs=4326)
gdf.head()

                                     Sport       Lat       Long  Trad  \
Area               Crag
10 Mile Canyon     10 Mile Tower       1.0  39.57010 -106.11985   0.0
Brick Wall/Alcoves Alcoves, The        0.0  39.56660 -106.12615   0.0
                   Brick Wall          0.0  39.56637 -106.12630   1.0
10 Mile Canyon     Cache Wall, The     6.0  39.56147 -106.13202   1.0
                   Desperation Wall    4.0  39.51999 -106.14030   2.0

                                     Toprope  Boulder  Alpine  Aid  Ice  \
Area               Crag
10 Mile Canyon     10 Mile Tower         0.0      0.0     0.0  0.0  0.0
Brick Wall/Alcoves Alcoves, The          0.0      0.0     0.0  0.0  0.0
                   Brick Wall            1.0      0.0     0.0  0.0  0.0
10 Mile Canyon     Cache Wall, The       0.0      0.0     0.0  0.0  0.0
                   Desperation Wall      3.0      3.0     0.0  0.0  0.0

                                     Mixed  Total Climbs  \
Area               Crag
10 Mile Canyon     10 Mile Tower       0.0           1.0
Brick Wall/Alcoves Alcoves, The        0.0           0.0
                   Brick Wall          0.0           2.0
10 Mile Canyon     Cache Wall, The     0.0           7.0
                   Desperation Wall    0.0          12.0

                                                        geometry
Area               Crag
10 Mile Canyon     10 Mile Tower     POINT (-106.11985 39.57010)
Brick Wall/Alcoves Alcoves, The      POINT (-106.12615 39.56660)
                   Brick Wall        POINT (-106.12630 39.56637)
10 Mile Canyon     Cache Wall, The   POINT (-106.13202 39.56147)
                   Desperation Wall  POINT (-106.14030 39.51999)

In [18]:
gdf = gdf.to_crs(epsg=3857)
gdf.head()

                                     Sport       Lat       Long  Trad  \
Area               Crag
10 Mile Canyon     10 Mile Tower       1.0  39.57010 -106.11985   0.0
Brick Wall/Alcoves Alcoves, The        0.0  39.56660 -106.12615   0.0
                   Brick Wall          0.0  39.56637 -106.12630   1.0
10 Mile Canyon     Cache Wall, The     6.0  39.56147 -106.13202   1.0
                   Desperation Wall    4.0  39.51999 -106.14030   2.0

                                     Toprope  Boulder  Alpine  Aid  Ice  \
Area               Crag
10 Mile Canyon     10 Mile Tower         0.0      0.0     0.0  0.0  0.0
Brick Wall/Alcoves Alcoves, The          0.0      0.0     0.0  0.0  0.0
                   Brick Wall            1.0      0.0     0.0  0.0  0.0
10 Mile Canyon     Cache Wall, The       0.0      0.0     0.0  0.0  0.0
                   Desperation Wall      3.0      3.0     0.0  0.0  0.0

                                     Mixed  Total Climbs  \
Area               Crag
10 Mile Canyon     10 Mile Tower       0.0           1.0
Brick Wall/Alcoves Alcoves, The        0.0           0.0
                   Brick Wall          0.0           2.0
10 Mile Canyon     Cache Wall, The     0.0           7.0
                   Desperation Wall    0.0          12.0

                                                              geometry
Area               Crag
10 Mile Canyon     10 Mile Tower     POINT (-11813207.665 4803665.639)
Brick Wall/Alcoves Alcoves, The      POINT (-11813908.978 4803160.209)
                   Brick Wall        POINT (-11813925.676 4803126.996)
10 Mile Canyon     Cache Wall, The   POINT (-11814562.423 4802419.439)
                   Desperation Wall  POINT (-11815484.149 4796431.759)

In [19]:
gdf.shape

(2659, 12)

In [20]:
gdf_buffer = gpd.GeoDataFrame(gdf.drop('geometry', axis=1), geometry=gdf.buffer(100, cap_style=3), crs=3857)
#gdf_buffer = gdf_buffer.to_crs(3857)

In [26]:
gdf_buffer.to_file('all_crags_3857_10m.geojson', driver='GeoJSON')

In [21]:
gdf_buffer.to_file('all_crags_final_3857_100m.shp', driver='ESRI Shapefile')

C:\Users\abreunig\AppData\Local\Temp\2\ipykernel_12904\311461025.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  gdf_buffer.to_file('all_crags_final_3857_100m.shp', driver='ESRI Shapefile')

In [23]:
all_crags = pd.DataFrame(all_crags, index=index)
all_crags

C:\Users\abreu\AppData\Local\Temp\ipykernel_7480\2170055293.py:1: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  all_crags = pd.DataFrame(all_crags, index=index)

ValueError: cannot reindex on an axis with duplicate labels

In [10]:
all_crags = all_crags.reset_index().rename(columns={'index': 'Crag'})

In [11]:
all_crags

,Crag,Sport,Lat,Long,Trad,Toprope,Boulder
0,10 Mile Tower,1.0,39.57010,-106.11985,NaN,NaN,NaN
1,Brick Wall/Alcoves,NaN,39.56649,-106.12626,1.0,1.0,NaN
2,"Cache Wall, The",6.0,39.56147,-106.13202,1.0,NaN,NaN
3,Desperation Wall,4.0,39.51999,-106.14030,2.0,3.0,3.0
4,"Diamond /Officer's Wall Massif, The",8.0,39.53802,-106.13790,1.0,NaN,1.0
5,"Dome, The",4.0,39.57073,-106.11763,12.0,NaN,NaN
6,Halfway Rock,9.0,39.53880,-106.13640,NaN,NaN,NaN
7,Mount Royal (near Frisco),2.0,39.57230,-106.11100,3.0,NaN,NaN
8,Officer's Gulch West,18.0,39.52984,-106.14082,NaN,1.0,NaN
9,"Shire, The",3.0,39.57229,-106.11700,NaN,1.0,NaN
10,Smile Wall,14.0,39.51990,-106.14022,NaN,NaN,NaN
11,Spider Boulder,NaN,39.51653,-106.14382,NaN,NaN,3.0
12,Sunshine Buttress (aka Wichita Wall),9.0,39.57091,-106.11832,14.0,NaN,1.0
13,"Sunshine, Ding Dong Dome Bouldering",NaN,39.57019,-106.11727,NaN,NaN,3.0
14,Teeter Top,5.0,39.56807,-106.12628,NaN,3.0,NaN
15,Wheeler Lakes,NaN,39.52117,-106.16838,NaN,1.0,NaN
16,White Cliff,16.0,39.56790,-106.12270,4.0,NaN,NaN

In [ ]:
index = pd.MultiIndex